<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>BG Admin</title>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
<?php Tag::css('kumbia') ?>
<link rel="stylesheet" href="assets/css/main.css">
<link rel="icon"  type="image/png" href="img/favicon.png">
<?php echo Html::includeCss() ?> 
</head>

  <?php View::content() ?>

<script src="assets/bundles/libscripts.bundle.js"></script>
<script src="assets/js/main.js"></script>
</html>
