<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>BG Admin</title>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
<?php Tag::css('kumbia') ?>
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/css/vendor/animsition.min.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/js/vendor/datetimepicker/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/js/vendor/chosen/chosen.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/css/main.css">
<?php echo Html::includeCss() ?> 
<link rel="icon"  type="image/png" href="http://bgreatsolutions.com/img/favicon.png">
</head>
<body id="oakleaf" class="main_Wrapper">
	<div id="wrap" class="animsition"> 
		<?php View::partial("admin/menu") ?>
		<?php View::partial("admin/nav") ?>
		<section id="content">
			<?php View::content() ?>
		</section>
	</div>
    
	<script src="http://bgreatsolutions.com/assets/bundles/libscripts.bundle.js"></script>
	<script src="http://bgreatsolutions.com/assets/bundles/vendorscripts.bundle.js"></script>
	<script src="http://bgreatsolutions.com/assets/js/vendor/chosen/chosen.jquery.min.js"></script> 
	<script src="http://bgreatsolutions.com/assets/js/vendor/filestyle/bootstrap-filestyle.min.js"></script> 
	<script src="http://bgreatsolutions.com/assets/js/main.js"></script> 
</body>
</html>