<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>BG Admin</title>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
<link rel="icon"  type="image/png" href="../img/favicon.png">
<?php Tag::css('kumbia') ?>
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/css/vendor/animsition.min.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/js/vendor/colorpicker/css/bootstrap-colorpicker.min.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/js/vendor/touchspin/jquery.bootstrap-touchspin.min.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/js/vendor/chosen/chosen.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/js/vendor/summernote/summernote.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/css/main.css">
<link rel="stylesheet" href="http://bgreatsolutions.com/assets/css/style.css">
<script src="//cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>
<?php echo Tag::js('jquery/jquery.min') ?>
<?php echo Tag::js('jquery/jquery.kumbiaphp') ?>

<?php echo Html::includeCss() ?> 

</head>
<body id="oakleaf" class="main_Wrapper">
	<div id="wrap" class="animsition"> 
		<?php View::partial("admin/menu") ?>
		<?php View::partial("admin/nav") ?>
		<section id="content">
			<?php View::content() ?>
		</section>
	</div>


	<script src="http://bgreatsolutions.com/assets/bundles/libscripts.bundle.js"></script>
	<script src="http://bgreatsolutions.com/assets/bundles/vendorscripts.bundle.js"></script>
	<script src="http://bgreatsolutions.com/assets/bundles/bootstrapscripts.bundle.js"></script>
	<script src="http://bgreatsolutions.com/assets/js/vendor/summernote/summernote.min.js"></script> 
	<script src="http://bgreatsolutions.com/assets/js/vendor/footable/footable.all.min.js"></script> 
	<script src="http://bgreatsolutions.com/assets/js/main.js"></script> 

	<script type="text/javascript">
	    $(window).load(function(){
	        $('#ex1').slider({
	            formatter: function(value) {
	                return 'Current value: ' + value;
	            }
	        });
	        $("#ex1").on("slide", function(slideEvt) {
	            $("#ex1SliderVal").text(slideEvt.value);
	        });

	        $("#ex2, #ex3, #ex4, #ex5").slider();

	        $('#summernote').summernote({
	            height: 200   
	        });
	      
	    });
	</script> 

	<script type="text/javascript">
	$(window).load(function(){
		$('.footable').footable();

	});
</script> 
</body>
</html>
