
<section class="comonSection terminos" style="background:#eee;padding-top:80px">
<style>
    .terminos p{
        color:#333 !important;
    }
</style>
            
                <div class="container" style="padding-top:80px">
                    <div class="row">
                        <div class="col-lg-12">
                            <h2 class="separate sectionTitle2" style="margin-bottom:20px;color:#AD2168">
                                <small style="color:#000;margin-bottom:0">Estamos para ti</small>
                                Mapa del Sitio <br>

                               
                            </h2>
                        </div>
                        <div class="col-lg-12">
                            <ul>
                                <li><a href="./#home">Inicio</a></li>
                                <li><a href="#nosotros">Nosotros</a>
                                    <ul>
                                        <li><a href="./#nosotros">Sobre Nosotros</a></li>
                                        <li><a href="./#trabajobg" >Trabaja en BG</a></li>
                                    </ul>
                                </li>                    
                                <li><a href="./#soluciones">Soluciones</a></li>
                                <li><a href="#" data-toggle="modal" data-target="#Grupobg">Se parte de BG</a></li>
                                <li><a href="#clientes">Nuestros Clientes</a>
                                    <ul>
                                        <li><a href="./#clientes">Clientes</a></li>
                                        <li><a href="./#testimonios" >Testimonios</a></li>
                                    </ul>
                                </li>    
                                <li><a href="./#blog">Blog</a></li>
                                <li><a href="./#contact">Contáctanos</a></li>
                                <li>Soporte</li>
                                    <ul>
                                        <li><?php echo Html::link("mapa","Mapa del sitio") ?></li>
                                        <li><?php echo Html::link("terminos","Términos del servicio") ?></li>
                                        <li><?php echo Html::link("politicas","Políticas de privacidad") ?></li>

                                      
                                    </ul>
                            </ul>

                        </div>
                        
                    </div>
                    
                </div>
               
            </section> 

<section class="callToAction2" style="padding-top:50px;background:#F38209">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-9 wow fadeInUp" data-wow-duration="700ms" data-wow-delay="300ms">
                <div class="callToActionContent2">
                    <h3 class="white">12 años de éxito y <span style="color:#3E4095">crecimiento</span></h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 wow fadeInUp" data-wow-duration="700ms" data-wow-delay="300ms">
                <a href="./#contact" class="btn-black" style="float:right">Contactar</a>
            </div>
        </div>
    </div>
</section>