	<section id="header">
		<header class="clearfix"> 
			<div class="branding"> <a class="brand" href="#"><?php echo Html::img("images/favicon.png","","width='30px' style='padding-right:5px'") ?><span>BG</span></a> <a role="button" tabindex="0" class="offcanvas-toggle visible-xs-inline"><i class="fa fa-th-large"></i></a> </div>
	
			
			<ul class="nav-right pull-right list-inline">
				<li><?php echo Html::link("admin/logout",'<i class="fa fa-sign-out"></i> Salir','') ?></li>
			</ul>
		</header>
	</section>