<div id="controls"> 
		<aside id="leftmenu">
			<div id="leftmenu-wrap">
				<div class="panel-group slim-scroll" role="tablist">
					<div class="panel panel-default">						
						<div id="leftmenuNav" class="panel-collapse collapse in" role="tabpanel">
							<div class="panel-body"> 
								<ul id="navigation">
									<li><?php echo Html::link("admin/config",'<i class="fa fa-dashboard"></i> <span>Principal</span>') ?></li>
									<li><?php echo Html::link("admin/general",'<i class="fa fa-arrow-right"></i> <span>Configuraciones Generales</span>') ?></li>
									<li><a role="button" tabindex="0"><i class="fa fa-photo"></i> <span>Banners</span></a>
										<ul>
											<li><?php echo Html::link("admin/banners",'<i class="fa fa-angle-right"></i> Listado') ?></li>
											<li><?php echo Html::link("admin/nuevo_banner",'<i class="fa fa-angle-right"></i> Agregar nuevo') ?></li>
										</ul>
									</li>
									<li> <a role="button" tabindex="0"><i class="fa fa-star"></i> <span>Nosotros</span></a>
										<ul>
											<li><?php echo Html::link("admin/nosotros",'<i class="fa fa-angle-right"></i> Datos Generales') ?></li>
											<li><?php echo Html::link("admin/parallax",'<i class="fa fa-angle-right"></i> Parallax - Cifras') ?></li>
											<li><?php echo Html::link("admin/equipo",'<i class="fa fa-angle-right"></i> Trabaja en BG') ?></li>
											
										</ul>
									</li>
									<li> <a role="button" tabindex="0"><i class="fa fa-magic"></i> <span>Soluciones</span></a>
										<ul>
											<li><?php echo Html::link("admin/soluciones",'<i class="fa fa-angle-right"></i> Listado') ?></li>
											<li><?php echo Html::link("admin/agregar_servicio",'<i class="fa fa-angle-right"></i> Agregar Servicio') ?></li>
										</ul>
									</li>
									<li> <a role="button" tabindex="0"><i class="fa fa-list"></i> <span>Clientes</span></a>
										<ul>
											<li><?php echo Html::link("admin/clientes",'<i class="fa fa-angle-right"></i> Listado') ?></li>
											<li><?php echo Html::link("admin/agregar_cliente",'<i class="fa fa-angle-right"></i> Agregar Nuevo') ?></li>
											<li><?php echo Html::link("admin/testimonios",'<i class="fa fa-angle-right"></i> Testimonios') ?></li>
											<li><?php echo Html::link("admin/agregar_testimonio",'<i class="fa fa-angle-right"></i> Agregar Testimonio') ?></li>
										</ul>
									</li>
									<li> <a role="button" tabindex="0"><i class="fa fa-book"></i> <span>Blog</span></a>
										<ul>
											<li><?php echo Html::link("admin/blog",'<i class="fa fa-angle-right"></i> Listado') ?></li>
											<li><?php echo Html::link("admin/agregar_blog",'<i class="fa fa-angle-right"></i> Agregar Noticia') ?></li>
										</ul>
									</li>
									<li><?php echo Html::link("admin/imagenes",'<i class="fa fa-photo"></i> <span>Carga de Imagenes</span>') ?></li>
									<li><?php echo Html::link("admin/cv",'<i class="fa fa-list"></i> <span>Postulaciones - CVs</span>') ?></li>
								
								</ul>
							</div>
						</div>
					</div>
				
				</div>
			</div>
		</aside>
	</div>