
<section class="comonSection terminos" style="background:#eee;padding-top:80px">
<style>
    .terminos p{
        color:#333 !important;
    }
</style>
            
                <div class="container" style="padding-top:80px">
                    <div class="row">
                        <div class="col-lg-12">
                            <h2 class="separate sectionTitle2" style="margin-bottom:20px;color:#AD2168">
                                <small style="color:#000;margin-bottom:0">Estamos para ti</small>
                                Políticas de Privacidad <br>

                               
                            </h2>
                        </div>
                        <div class="col-lg-12">
                            <?php echo $info->politicas ?>
                        </div>
                        
                    </div>
                    
                </div>
               
            </section> 

<section class="callToAction2" style="padding-top:50px;background:#F38209">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-9 wow fadeInUp" data-wow-duration="700ms" data-wow-delay="300ms">
                <div class="callToActionContent2">
                    <h3 class="white">12 años de éxito y <span style="color:#3E4095">crecimiento</span></h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 wow fadeInUp" data-wow-duration="700ms" data-wow-delay="300ms">
                <a href="./#contact" class="btn-black" style="float:right">Contactar</a>
            </div>
        </div>
    </div>
</section>