<section class="comonSection" style="background:#eee;padding-top:80px">
            
                <div class="container" style="padding-top:80px">
                    <div class="row">
                        <div class="col-lg-12">
                            <h2 class="separate sectionTitle2" style="margin-bottom:20px;color:#D45E03">
                                <?php $categ = Load::model("categoriablog")->find_by_id("$blog->categoriablog_id"); ?>
                                <small style="color:#000;margin-bottom:0"><?php echo $categ->nombre ?></small>
                                <?php echo $blog->titulo ?> <br>

                                <a href="#" style="font-size:14px;color:#333"><i class="esen-Calendar" style="font-size:16px;margin-right:10px"></i><?php echo $blog->fecha ?></a>

                            </h2>
                        </div>
                        
                    </div>
                    <div class="row">
                        <div class="col-lg-3 color-gris">
                            <?php echo Html::img($blog->img,"",'width="100%" style="padding-top:20px;padding-bottom:20px"') ?>
                
                        </div>
                        <div class="col-lg-9 color-gris" style="padding-top:10px">
                            <?php echo $blog->texto ?>
                           

                        </div>
                    </div>
                </div>
               
            </section> 

<section class="callToAction2" style="padding-top:50px;background:#F38209">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-9 wow fadeInUp" data-wow-duration="700ms" data-wow-delay="300ms">
                <div class="callToActionContent2">
                    <h3 class="white">12 años de éxito y <span style="color:#3E4095">crecimiento</span></h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 wow fadeInUp" data-wow-duration="700ms" data-wow-delay="300ms">
                <a href="./#contact" class="btn-black" style="float:right">Contactar</a>
            </div>
        </div>
    </div>
</section>