
        <div class="col-md-12 modal fade" id="Grupobg" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
           <div class="modal-dialog" style="background:#fff">
              <div class="modal-content" style="border-radius:0;background:#fff;border:0">
                    <div class="col-md-12 modal-header" style="background:#fff;border-top:3px solid #F28109">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <h5 class="modal-title" id="myModalLabel"><img src="../../img/favicon.png" alt="" width="20px" style="margin-right:10px">Equipo B&G</h5>
                    </div>
                    <div class="col-md-12 modal-body" style="margin-top:0;background:#fff">
                        <div class="funfacts2 text-center color-gris">
                                <h3 class="separate" style="margin-bottom:10px;">
                                <small style="color:#AD2168;margin-bottom:0">Se parte del Equipo B&G</small>
                                </h3>
                                <p>En B&G constantemente estamos en la búsqueda de los mejores talentos para formar parte de nuestra organización o para captar talentos para nuestros clientes, déjanos tus datos, resumen curricular y tus áreas de experiencia para que ser ubicado en el mejor lugar de trabajo</p>

                                <form class="conForms conforms2" method="post" action="#" id="" style="margin-top:20px;" enctype="multipart/form-data">
                                    <div class="col-md-12">
                                        <input type="text" name="nombre" id="nombre" class="inputa required" placeholder="Nombre Completo"/>
                                    </div>
                                     <div class="col-md-6">
                                        <input type="text" name="telefono" id="telefono" class="inputa required" placeholder="Telefono"/>
                                    </div>
                                     <div class="col-md-6">
                                        <input type="email" name="email" id="email" class="inputa required" placeholder="Email"/>
                                    </div>
                                    <div class="col-md-12">
                                        <input type="text" name="profesion" id="profesion" class="inputa required" placeholder="Profesión"/>
                                    </div>
                                     <div class="col-md-6">
                                        <input type="text" name="area" id="area" class="inputa required" placeholder="área de experiencia"/>
                                    </div>
                                     <div class="col-md-6">
                                        <input type="text" name="grado" id="grado" class="inputa required" placeholder="Grado de Instrucción"/>
                                    </div>
                                    <div class="col-md-12">
                                        <textarea class="texputa required" id="mensaje" name="mensaje" placeholder="Comentarios"></textarea>
                                    </div>
                                    <div class="col-md-6">
                                        <div class='custom-input-file' style="float:left"><input type="file" name="adjunto" id="adjunto">Adjuntar CV</div>
                                    </div>
                                    <div class="col-md-6 text-center">
                                        <button type="submit" class="btn-morado" id="con_submit" style="border:0;padding:6px;font-size:12px;width:100%;">Aplicar ahora</button>
                                    </div>
                                    <div class="col-md-12" style="margin-top:10px;"><p>Adjunto: <span id="textadjunto"></span></p></div>
                                </form>
                        </div>
                    </div>
                 
                    <div class="col-md-12 modal-footer" style="background:#fff">
                        <a href="#" data-dismiss="modal" class="btn btn-warning" style="border:0;border-radius:0">Cerrar</a>
                    </div>
              </div>
           </div>
        </div>