<?php $info=Load::model("general")->find_by_id("1"); ?>
        <!--trabajo con nosotros-->

        <div class="col-md-12 modal fade" id="Grupobg" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
           <div class="modal-dialog" style="background:#fff">
              <div class="modal-content" style="border-radius:0;background:#fff;border:0">
                    <div class="col-md-12 modal-header" style="background:#fff;border-top:3px solid #F28109">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <h5 class="modal-title" id="myModalLabel"><?php echo Html::img("favicon.png",'','alt="" width="20px" style="margin-right:10px"') ?>Equipo BG</h5>
                    </div>
                    <div class="col-md-12 modal-body" style="margin-top:0;background:#fff">
                        <div class="funfacts2 text-center color-gris">
                                <h3 class="separate" style="margin-bottom:10px;">
                                <small style="color:#AD2168;margin-bottom:0">Se parte del Equipo BG</small>
                                </h3>
                                <p>En BG constantemente estamos en la búsqueda de los mejores talentos para formar parte de nuestra organización o para captar talentos para nuestros clientes, déjanos tus datos, resumen curricular y tus áreas de experiencia para que ser ubicado en el mejor lugar de trabajo</p>

                                <?php echo Form::openMultipart() ?>

                                <div class="conForms conforms2" style="margin-top:20px;">
                                    <div class="col-md-12">
                                         <?php echo Form::text("postulaciones.nombre",'placeholder="Nombre Completo*" class="inputa required" required') ?>
                                    </div>
                                     <div class="col-md-6">
                                         <?php echo Form::text("postulaciones.telefono",'placeholder="Teléfono *" class="inputa required" required') ?>
                                    </div>
                                     <div class="col-md-6">
                                        <?php echo Form::email("postulaciones.email",'placeholder="Email *" class="inputa required" required') ?>
                                    </div>
                                    <div class="col-md-12">
                                        <?php echo Form::text("postulaciones.profesion",'placeholder="Profesión *" class="inputa required" required') ?>
                                    </div>
                                     <div class="col-md-6">
                                        <?php echo Form::text("postulaciones.area",'placeholder="área de experiencia *" class="inputa required" required') ?>
                                    </div>
                                     <div class="col-md-6">
                                        <?php echo Form::text("postulaciones.grado",'placeholder="Grado de Instrucción *" class="inputa required" required') ?>
                                    </div>
                                    <div class="col-md-12">
                                        <select name="pais" id="pais" class="inputa required"">
                                            <option value="-">País al cual se postula</option>
                                            <option value="Venezuela">Venezuela</option>
                                            <option value="Estados Unidos">Estados Unidos</option>
                                            <option value="Panamá">Panamá</option>
                                        </select>
                                    </div>
                                    <div class="col-md-12">
                                        <textarea class="texputa required" id="mensaje" name="mensaje" placeholder="Comentarios"></textarea>
                                    </div>
                                    <div class="col-md-6">
                                        <div class='custom-input-file' style="float:left"><input type="file" name="adjunto" id="adjunto">Adjuntar CV - Límite 10MB</div>
                                    </div>
                                    <div class="col-md-6 text-center">
                                        <button type="submit" class="btn-morado" id="con_submit" style="border:0;padding:6px;font-size:12px;width:100%;">Aplicar ahora</button>
                                    </div>
                                    <div class="col-md-12" style="margin-top:10px;"><p>Adjunto: <span id="textadjunto"></span></p></div>

                                </div>
                              <?php echo Form::close(); ?>
                        </div>
                    </div>
                 
                    <div class="col-md-12 modal-footer" style="background:#fff">
                        <a href="#" data-dismiss="modal" class="btn btn-warning" style="border:0;border-radius:0">Cerrar</a>
                    </div>
              </div>
           </div>
        </div>

  