<div class="page static-page-tables"> 
            <!-- bradcome -->
            <div class="bg-light lter b-b wrapper-md mb-10">
                <div class="row">
                    <div class="col-sm-6 col-xs-12">
                        <h1 class="font-thin h3 m-0">BG</h1>
                        <small class="text-muted">Bienvenido al administrador</small> </div>

                </div>
                <div class="row">
                    <div class="col-sm-12">
                         <?php echo Html::link("admin/categoriablog",'<i class="fa fa-magic"></i> Categorias de Noticias','class="btn btn-raised btn-primary fileinput-button"') ?>
                        <?php echo Html::link("admin/agregar_blog",'<i class="glyphicon glyphicon-plus"></i> Agregar Noticia','class="btn btn-raised btn-success fileinput-button"') ?>
                    </div>
                </div>
            </div>
            
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <section class="boxs ">
                        <div class="boxs-header dvd dvd-btm">
                            <h1 class="custom-font"><strong>Noticias</strong></h1>
                            
                        </div>
                        <div class="boxs-body p-0">
                            <div class="table-responsive">
                                         <table class="table table-middle">
                                    <thead>
                                        <tr>
                                            <th>Imagen</th>
                                            <th>Titulo</th>
                                            <th style="width:10%">Fecha</th>
                                            <th>Descripcion</th>
                                            <th style="width:15%">Operaciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($blog as $value) {
                                            echo
                                            '
                                             <tr>
                                             <td>'.Html::img($value->img,"","width='50px' style='border-radius:0px !important'").'</td>
                                            <td>'.$value->titulo.'</td>
                                            <td>'.$value->fecha.'</td>
                                            <td>'.$value->descripcion.'</td>
                                            <td class="btn-operation">
                                                '.Html::link("admin/editar_blog/$value->id",'<i class="fa fa-edit"></i>','class="btn btn-sm btn-success"').'
                                                '.Js::link("admin/deleteblog/$value->id",'<span class="btn btn-sm btn-danger"><i class="fa fa-trash-o"></i></span>',"¿Esta segur@ que desea eliminar esta noticia?").'    
                                            </td>
                                            </tr>
                                        ';
                                        } ?>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
         