		<div class="page profile-page" style="padding-bottom:0">
			<div class="pagecontent"> 
				<div class="bg-light lter b-b wrapper-md mb-10">
						<div class="row">
							<div class="col-sm-6 col-xs-12">
								<h1 class="font-thin h3 m-0">BG</h1>
								<small class="text-muted">Bienvenido al administrador</small>
							</div>
						</div>
					</div>
				<div class="row">
						<div class="col-md-12">
						<section class="boxs boxs-simple">
                            <div class="profile-header">
                                <div class="profile_info">
                                    <div class="profile-image">
                                        <?php echo Html::img("images/avatar5.png") ?>
                                    </div>
                                   <h4 class="mb-0"><strong><?php echo Auth::get("usuario") ?></strong></h4>
                                   	<?php if (Auth::get("admin")=='1'): ?>
                                    	<span class="text-muted">Administrador</span>
                                	<?php else: ?>
                                		<span class="text-muted">Editor</span>
                                	<?php endif ?>
              
                                </div>
                            </div>
                            
						</section>						
					</div>
				</div>
			</div>
		</div>				
		<div class="page page-timeline">
			
			<div class="pagecontent">
				<div class="row"> 
					<div class="col-md-12"> 
						<section class="tile-simple bg-white">
							<div class="tile-body streamline timeline p-0">
								<ul>
									<li class="timeline-post">
										<aside>
											<div class="thumb wh30 bg-lightred br-50"><i class="fa fa-lock"></i></div>
										</aside>
										<div class="post-container">
											<div class="panel panel-default">
												<h3 class="custom-font text-danger">Campos Obligatorios</h3>
												<p>Es importante tener en cuenta que hay campos obligatorios, los cuales permiten que el sitio web se visualice correctamente.</p>
											</div>
										</div>
									</li>
									<li class="timeline-post">
										<aside>
											<div class="thumb wh30 bg-blue br-50"><i class="fa fa-clock-o"></i></div>
										</aside>
										<div class="post-container">
											<div class="panel panel-default">
												<h3 class="custom-font text-blue">Soporte</h3>
												<p>En caso de algun error de la app, se debe informar a soporte a traves del correo <a href="mailto:info@steffdesign.com">info@steffdesign.com</a> </p>
											</div>
										</div>
									</li>
									
									
								</ul>
							</div>
						</section>
					</div>
				</div>
			</div>
		</div>