    <div class="page profile-page" style="padding-bottom:0">
            <div class="pagecontent"> 
                <div class="bg-light lter b-b wrapper-md mb-10">
                        <div class="row">
                            <div class="col-sm-6 col-xs-12">
                                <h1 class="font-thin h3 m-0">BG</h1>
                                <small class="text-muted">Bienvenido al administrador</small>
                            </div>
                        </div>
                    </div>
                <div class="row">
                     <div class="col-md-12"> 
                        <section class="boxs boxs-simple"> 
                            <div class="boxs-body p-0">
                                <div role="tabpanel"> 
                                    <ul class="nav nav-tabs tabs-dark-t" role="tablist">
                                        <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">Cronología</a></li>
                                    </ul>
                                    
                                    <div class="tab-content">
                                         <div role="tabpanel" class="tab-pane active" id="general">
                                            <div class="wrap-reset">
                                                <?php echo Form::openMultipart(); ?>
                                                <form class="profile-settings">
                             
                                                    <div class="row">
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Titulo *</label>
                                                            <?php echo Form::text('cronologia.titulo','class="form-control" autofocus required') ?>
                                                        </div>
                                                        <div class="form-group col-md-12">
                                                            <label for="last-name">Texto *</label>
                                                            <?php echo Form::textarea('cronologia.texto','class="form-control" required') ?>
                                                        </div>
                                                    </div>
                                                                                                  
                                                    <hr>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <?php echo Html::link("admin/config","Cancelar","class='btn btn-raised btn-default'") ?>
                                                            <button type="submit" value="submit" class="btn btn-raised btn-primary">Agregar</button>
                                                        </div>
                                                    </div>
                                                </form>
                                                <?php echo Form::close(); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>  

<div class="page static-page-tables"> 
            <div class="row">
                <div class="col-md-12">
                    <section class="boxs ">
                        <div class="boxs-header dvd dvd-btm">
                            <h1 class="custom-font"><strong>Nuestra </strong> Cronología</h1>
                            
                        </div>
                        <div class="boxs-body p-0">
                            <div class="table-responsive">
                                <table class="table table-middle">
                                    <thead>
                                        <tr>
                                      
                                            <th style="width:30%">Titulo</th>
                                            <th>Descripcion</th>
                                            <th style="width:20%">Operaciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($cronologia as $value) {
                                           
                                            echo
                                            '
                                            <tr>
                                            <td>'.$value->titulo.'</td>
                                            <td>'.$value->texto.'</td>
                                            <td class="btn-operation">
                                                '.Html::link("admin/editar_cronologia/$value->id",'<i class="fa fa-edit"></i>','class="btn btn-sm btn-success"').'
                                                '.Js::link("admin/deletecronologia/$value->id",'<span class="btn btn-sm btn-danger"><i class="fa fa-trash-o"></i></span>',"¿Esta segur@ que desea eliminar este item?").'    
                                            </td>
                                            </tr>
                                        ';
                                        } ?>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
