<div class="page static-page-tables"> 


            <div class="bg-light lter b-b wrapper-md mb-10">
                <div class="row">
                    <div class="col-sm-6 col-xs-12">
                        <h1 class="font-thin h3 m-0">Postulaciones</h1>
                        <small class="text-muted">CVs</small> </div>

                </div>
            </div>

            


             <div class="row">
                <div class="col-md-12">
                    <section class="boxs ">
                        <div class="boxs-body p-0">
                            <div class="table-responsive">
                                <table id="searchTextResults" data-page-size="5" data-filter="#filter"  class="footable table table-custom">
                                    <thead>
                                        <tr>
                                            
                                            <th style="font-size:12px">Nombre</th>
                                            <th style="font-size:12px">Telefono</th>
                                            <th style="font-size:12px">Email</th>
                                            <th style="font-size:12px">Profesion</th>
                                            <th style="font-size:12px">Area</th>
                                            <th style="font-size:12px">Grado</th>
                                            <th style="font-size:12px">País al cual se postula</th>
                                            <th style="font-size:12px">Fecha</th>
                                            <th style="font-size:12px">Mensaje</th>
                                            <th style="font-size:12px">CV</th>
                                        </tr>
                                    </thead>
                                     <tbody>
                                        <?php foreach ($postulaciones as $values) {
                                            echo
                                            '
                                             <tr>
                                            <td style="font-size:12px">'.$values->nombre.'</td>
                                            <td style="font-size:12px">'.$values->telefono.'</td>
                                            <td style="font-size:12px">'.$values->email.'</td>
                                            <td style="font-size:12px">'.$values->profesion.'</td>
                                            <td style="font-size:12px">'.$values->area.'</td>
                                            <td style="font-size:12px">'.$values->grado.'</td>
                                            <td style="font-size:12px">'.$values->pais.'</td>
                                            <td style="font-size:12px">'.$values->fecha.'</td>
                                            <td style="font-size:12px">'.$values->mensaje.'</td>
                                            <td class="btn-operation">
                                                '.Html::link('files/'.$values->adjunto,Html::img("cv.png","","width='20px' style='border-radius:0 !important'"),'target="_blank"').'    
                                            </td>

                                            </tr>
                                        ';
                                        } ?>

                                    </tbody>
                                    <tfoot class="hide-if-no-paging">
                                    <tr>
                                        <td colspan="5" class="text-right"><ul class="pagination">
                                            </ul></td>
                                    </tr>
                                </tfoot>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
