        <div class="page profile-page" style="padding-bottom:0">
            <div class="pagecontent"> 
                <div class="bg-light lter b-b wrapper-md mb-10">
                        <div class="row">
                            <div class="col-sm-6 col-xs-12">
                                <h1 class="font-thin h3 m-0">BG</h1>
                                <small class="text-muted">Bienvenido al administrador</small>
                            </div>
                        </div>
                    </div>
                <div class="row">
                     <div class="col-md-12"> 
                        <section class="boxs boxs-simple"> 
                            <div class="boxs-body p-0">
                                <div role="tabpanel"> 
                                    <ul class="nav nav-tabs tabs-dark-t" role="tablist">
                                        <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">Editar Testimonio</a></li>
                                    </ul>
                                    
                                    <div class="tab-content">
                                         <div role="tabpanel" class="tab-pane active" id="general">
                                            <div class="wrap-reset">
                                                <?php echo Form::openMultipart(); ?>
                                                <form class="profile-settings">
                                                    <div class="row">
                                                        <div class="form-group col-md-12 legend">
                                                            <h4><strong>Datos</strong> Testimonio</h4>
                                                            <p>Info de Cliente</p>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-4">
                                                            <label for="first-name">Nombre *</label>
                                                            <?php echo Form::text('testimonios.nombre','class="form-control"') ?>
                                                        </div>
                                                         <div class="form-group col-md-4">
                                                            <label for="first-name">Cargo *</label>
                                                            <?php echo Form::text('testimonios.cargo','class="form-control"') ?>
                                                        </div>
                                                         <div class="col-md-4">
                                                             <label for="first-name">Empresa</label>
                                                            <select name="testimonios[empresa]" class="form-control mb-10" data-parsley-trigger="change" data-parsley-id="1064">
                                                                <option value="<?php echo $testimonios->empresa ?>"><?php echo $testimonios->empresa ?></option>
                                                                <option value="-">Seleccione..</option>
                                                                <?php foreach ($clientes as $value) {
                                                                    echo '<option value="'.$value->nombre.'">'.$value->nombre.'</option>';
                                                                } ?>
                                                            </select>
                                                        </div>
                                                         <div class="form-group col-md-12">
                                                            <label for="first-name">Texto</label>
                                                            <?php echo Form::textarea('testimonios.texto','class="form-control"') ?>
                                                        </div>
                                                    </div>
                                                     
                                                    <div class="row">
                                                        <div class="col-md-4" style="margin-bottom:20px">
                                                            <div class='custom-input-file' style="width:100%"><?php echo Form::file('images',"","") ?>Imagen (100x100 o 50x50 px)</div>
                                                        </div>
                                                    </div>                                                
                                                    <hr>
                                                     <div class="row">
                                                        <div class="form-group col-md-12 legend">
                                                            <h4><strong>Datos</strong> Video</h4>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Url Youtube *</label>
                                                            <?php echo Form::text('testimonios.url','class="form-control"') ?>
                                                        </div>    
                                                         <div class="col-md-4" style="margin-bottom:20px">
                                                             <div class='custom-input-file' style="width:100%"><?php echo Form::file('img_video',"","") ?>Imagen (500x300px)</div>
                                                        </div>                                                   
                                                    </div>

                                                    <hr>
                                                    <?php echo Form::hidden("testimonios.id") ?>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <?php echo Html::link("admin/testimonios","Cancelar","class='btn btn-raised btn-default'") ?>
                                                            <button type="submit" value="submit" class="btn btn-raised btn-primary">Editar</button>
                                                        </div>
                                                    </div>
                                                </form>
                                                <?php echo Form::close(); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>  
