    <div class="page profile-page" style="padding-bottom:0">
            <div class="pagecontent"> 
                <div class="bg-light lter b-b wrapper-md mb-10">
                    <div class="row">
                        <div class="col-sm-6 col-xs-12">
                            <h1 class="font-thin h3 m-0">BG</h1>
                            <small class="text-muted">Bienvenido al administrador</small>
                        </div>
                    </div>
                </div>
                <div class="row">
                     <div class="col-md-12"> 
                        <section class="boxs boxs-simple"> 
                            <div class="boxs-body p-0">
                                <div role="tabpanel"> 
                                    <ul class="nav nav-tabs tabs-dark-t" role="tablist">
                                        <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">Editar</a></li>
                                    </ul>
                                    
                                    <div class="tab-content">
                                         <div role="tabpanel" class="tab-pane active" id="general">
                                            <div class="wrap-reset">
                                                <?php echo Form::openMultipart(); ?>
                                                <form class="profile-settings">
                                                    <div class="row">
                                                        <div class="form-group col-md-12 legend">
                                                            <h4><strong>Trabaja</strong> con BG</h4>
                                                            <p><?php echo $equipo->nombre ?></p>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Titulo *</label>
                                                            <?php echo Form::text('equipo.nombre','class="form-control" autofocus required') ?>
                                                        </div>
                                 
                                                        <div class="form-group col-md-12">
                                                            <label for="last-name">Texto *</label>
                                                            <?php echo Form::textarea('equipo.texto','class="form-control" required') ?>
                                                        </div>
                                                        <div class="col-md-12">
                                                            <?php echo Html::img($equipo->img,"","width='200px' style='margin-bottom:10px'") ?>
                                                        </div>
                                                        <div class="col-md-12" style="margin-bottom:20px">
                                                            <div class='custom-input-file' style="float:left"><?php echo Form::file('images',"","") ?>Imagen 400x290px</div>
                                                        </div>
                                             
                                                    </div>
                                                    <?php echo Form::hidden("equipo.id"); ?>                                       
                                                    <hr>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <?php echo Html::link("admin/equipo","Cancelar","class='btn btn-raised btn-default'") ?>
                                                            <button type="submit" value="submit" class="btn btn-raised btn-primary">Editar</button>
                                                        </div>
                                                    </div>
                                                </form>
                                                <?php echo Form::close(); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
 <script>
 CKEDITOR.replace( 'equipo[texto]' );
</script>