<?php View::content() ?>
<body class="signup-page">
<div class="wrapper">
  <div class="header header-filter" style="background-image: url('img/slider1.jpg'); background-size: cover; background-position: top center;">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 text-center">
          <div class="card card-signup">
            <form class="form" method="post" action="">
              <div class="header header-primary text-center">
                <?php echo Html::img("bg_blanco.png","","width='70%'") ?> 
              </div>
              <h3 class="mt-0">Log In</h3>
              <p class="help-block">Personal Autorizado</p>
              <div class="content">
                <div class="form-group">
                  <?php echo Form::text('user.usuario','placeholder="Usuario" class="form-control underline-input" autofocus required') ?>
                </div>
                <div class="form-group">
                  <?php echo Form::pass('user.clave','placeholder="Contraseña" class="form-control underline-input" required') ?>
                </div>
               
              </div>
              <div class="footer text-center">
                <button type="submit" value="submit" class="btn btn-primary btn-raised">
                  Ingresar<div class="ripple-container"></div>
                </button>
              
              </div>
             
            </form>
          </div>
        </div>
      </div>
    </div>
  
  </div>
</div>
</body>