<div class="page static-page-tables"> 
            <!-- bradcome -->
            <div class="bg-light lter b-b wrapper-md mb-10">
                <div class="row">
                    <div class="col-sm-6 col-xs-12">
                        <h1 class="font-thin h3 m-0">BG</h1>
                        <small class="text-muted">Bienvenido al administrador</small> </div>

                </div>
                <div class="row">
                    <div class="col-sm-12">
                         <?php echo Html::link("admin/soluciones",'<i class="fa fa-magic"></i> Listado de Soluciones','class="btn btn-raised btn-primary fileinput-button"') ?>
                        <?php echo Html::link("admin/agregar_item/$servicios->id",'<i class="glyphicon glyphicon-plus"></i> Agregar Item','class="btn btn-raised btn-success fileinput-button"') ?>
                    </div>
                </div>
            </div>
            
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <section class="boxs ">
                        <div class="boxs-header dvd dvd-btm">
                            <h1 class="custom-font"><strong>Servicio -</strong> <?php echo $servicios->titulo ?></h1>
                            
                        </div>
                        <div class="boxs-body p-0">
                            <div class="table-responsive">
                                         <table class="table table-middle">
                                    <thead>
                                        <tr>
                                            <th>Titulo</th>
                                            <th style="width:15%">Operaciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($items as $value) {
                                            echo
                                            '
                                             <tr>
                                            <td>'.$value->titulo.'</td>
                                            <td class="btn-operation">
                                                '.Html::link("admin/editar_item/$value->id/$servicios->id",'<i class="fa fa-edit"></i>','class="btn btn-sm btn-success"').'
                                                '.Js::link("admin/deleteitem/$value->id/$servicios->id",'<span class="btn btn-sm btn-danger"><i class="fa fa-trash-o"></i></span>',"¿Esta segur@ que desea eliminar este item?").'    
                                            </td>
                                            </tr>
                                        ';
                                        } ?>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
            <hr>
            <div class="bg-light lter b-b wrapper-md mb-10">
                <div class="row">
                    <div class="col-sm-6 col-xs-12">
                        <h1 class="font-thin h3 m-0">Imagenes</h1>
                        <small class="text-muted">Para utilizar usar url y colocar en editores</small> </div>

                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <?php echo Form::openMultipart() ?>
                            <div class='custom-input-file' style="float:left"><input type="file" multiple="multiple" name="imagenes[]" style="margin-top:10px;">Seleccionar imagenes</div>
                            <?php echo Form::hidden("imagenes",null,"asd") ?><br>
                            
                            <p class="col-sm-12" style="font-size:12px;margin-top:20px"><span class="label label-important">!</span> - Formatos permitidos <code>.JPG</code>, <code>.JPEG</code>, <code>.PNG</code></p>
                            <br>

                            <?php echo Form::submit("Agregar","class='btn btn-raised btn-primary' style='float:left;'") ?>
                        <?php echo Form::close() ?>
                    </div>
                </div>
            </div>

            


             <div class="row">
                <div class="col-md-12">
                    <section class="boxs ">
                        <div class="boxs-body p-0">
                            <div class="table-responsive">
                                <table id="searchTextResults" data-page-size="5" data-filter="#filter"  class="footable table table-custom">
                                    <thead>
                                        <tr>
                                      
                                            <th>Imagen</th>
                                            <th>Url</th>
                                        </tr>
                                    </thead>
                                     <tbody>
                                        <?php foreach ($imagenes as $values) {
                                            echo
                                            '
                                             <tr>
                                            <td>'.Html::img($values->img,"","style='width:70px;border-radius:0px !important'").'</td>
                                            <td>http://bgreatsolutions.com/img/'.$values->img.'</td>

                                            </tr>
                                        ';
                                        } ?>

                                    </tbody>
                                    <tfoot class="hide-if-no-paging">
                                    <tr>
                                        <td colspan="5" class="text-right"><ul class="pagination">
                                            </ul></td>
                                    </tr>
                                </tfoot>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
